aeternity/aepp-calldata-js

Makefile
contracts/Test.aes
tests/contract-call.sh

Not sure why the tests was passing on master with broken source (missing interface)

Add contact call wrapper

---

CHANGELOG.md
CONTRIBUTING.md
README.md
package-lock.json
package.json
src/DataFactory.js
tests/Encoder.js

Add documentation

---

README.md
src/Encoder.js
tests/Encoder.js

Add decodeString piblic API

---

README.md
src/DataFactory.js
src/types/FateVariant.js
tests/Decoder.js
tests/Encoder.js

Support option type as exact value and null alongside variants

---

src/types/FateBool.js
tests/Serializers/BoolSerializer.js

This reverts commit 87fa067b4585a748bbe2ca3202e4f5c9cbd9d963.
https://github.com/aeternity/aepp-calldata-js/pull/76#issuecomment-956035785

Revert "Strict boolean validation in FateBool (#76)"

---

README.md
src/Encoder.js

- minimize the interface
- use private fields
- add JSDoc

Revamp public API

---

package-lock.json
package.json
src/Encoder.js
src/utils/base64check.js

Replace base64check implementation

---

src/types/FateVariant.js

Fix class method declaration

---

package-lock.json
package.json
src/utils/hash.js

They've released changes that we need at 1.1.2

Switch to upstream version of blakejs

---

.github/workflows/main.yml
Makefile
package-lock.json
package.json
tests/Decoder.js
tests/Encoder.js
tests/benchmark/decoder.js
tests/benchmark/encoder.js

Benchmarks

---

src/utils/base64check.js
src/utils/hash.js

related PR: https://github.com/aeternity/aepp-sdk-js/pull/1623

Import specific versions of blakejs and sha.js

---

.github/workflows/main.yml
.github/workflows/publish.yml

Fix npm auth

---

package-lock.json
package.json
tests/contract-call.sh

depends on https://github.com/aeternity/aepp-cli-js/pull/194 and a new cli release
and https://github.com/aeternity/aepp-cli-js/pull/196

Update aecli to 4.1.0

---

README.md
src/AciContractCallEncoder.js
src/BytecodeContractCallEncoder.js
src/Encoder.js
src/api/FateApiEncoder.js
src/main.d.ts
src/main.js
src/types/FateString.js
src/utils/base58check.js
src/utils/base64check.js
tests/ApiEncoder.js
tests/api.js

fixes #168
*on hold until I get reasonable use-case in #168*

Add FateApiEncoder to public API

---

src/ApiEncoder.js
tests/ApiEncoder.js

This PR is sponsored by the Aeternity Crypto Foundation

Add support for more encoders

---

package.json

Hint webpack the lib is side effects free

---

package-lock.json
package.json
tests/contract-call.sh

This PR is supported by the Æternity Foundation

Update aecli to 6.0.0

---

src/Serializers/TypeSerializer.js
tests/Serializers/TypeSerializer.js

This PR is supported by the Æternity Foundation

Implement `serialize` in TypeSerializer

---

package-lock.json

extracted from #268
This PR is supported by the Æternity Foundation

Regenerate package-lock

---

package-lock.json
package.json
tests/contract-call.sh

This PR is supported by the Æternity Foundation
https://github.com/aeternity/aepp-cli-js/releases/tag/v7.0.0
replaces #305

chore: update aecli to 7.0.0
